export const projectCards = [
  {
    id: 0,
    cardName: "Better Stewards",
    techStack: "FrontEnd",
    imageUrl: `${process.env.PUBLIC_URL}/images/better-steward2.avif`,
    released: true,
    releaseDate: "02/17/2024",
    siteUrl: "https://betterstewards.org/",
    description:
      "I've developed a WordPress website aimed at enhancing the promotion efforts of the Better Stewards non-profit organization. This platform serves as a comprehensive online presence, showcasing the organization's mission, initiatives, and impact. Through intuitive design and engaging content, the website aims to amplify awareness and support for Better Stewards' important work within the community.",
    techUsed: ["Wordpress", "JavaScript", "MySQL", "CPanel"],
    filters: ["wordpress", "javascript", "frontend", "mysql"],
  },
  {
    id: 1,
    cardName: "Twitch Bot",
    techStack: "Hybrid",
    imageUrl: `${process.env.PUBLIC_URL}/images/twitch-bot2.avif`,
    released: true,
    releaseDate: "12/20/2023",
    siteUrl: "",
    description: `I've created a desktop application designed to seamlessly interface with Twitch.tv, specifically tailored to automatically engage in the Twitch game "Pokémon Community Game." This app streamlines the process, allowing users to participate effortlessly in the collective gaming experience without manual intervention.`,
    techUsed: ["Electron", "JavaScript"],
    filters: ["electron", "javascript", "frontend", "released", "nodejs"],
  },
  {
    id: 2,
    cardName: "Laundromat Express",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/washer2.jpeg`,
    released: false,
    releaseDate: "N/A: In Development",
    siteUrl: "https://github.com/0112Derrick/Laundromat-Hub",
    description:
      "I have a vision for revolutionizing the way people pay for laundry services. I am developing an app that will enable users to pay for washing machine usage using their debit or credit cards directly from their smartphones, eliminating the need for searching for quarters. This innovation promises benefits for both customers and Laundromat owners, providing real-time visibility into machine usage for better management and convenience.",
    techUsed: ["ReactJS", "Asp.Net", "Bootstrap"],
    filters: [
      "react",
      "asp.net",
      "javascript",
      "typescript",
      "fullstack",
      "bootstrap",
    ],
  },
  {
    id: 3,
    cardName: "Gees Clippers",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/gee.png`,
    released: false,
    releaseDate: "N/A",
    siteUrl: "https://github.com/0112Derrick/GeesClippersTechTitans-Personal",
    description:
      "I worked on a project during my time with i.c.stars that revitalized a barbershop's corporate website. This involved integrating videos and implementing a content management system, enabling barbers to upload haircut photos and administrators to post real-time events. Additionally, the system included a review feature, facilitating communication between the barbershop and its community.",
    techUsed: ["HTML5", "CSS3", "TypeScript", "NodeJs", "ExpressJS"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 4,
    cardName: "Wizards Dream",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/castle.jpg`,
    released: false,
    releaseDate: "N/A: In Development",
    siteUrl: "https://github.com/0112Derrick/Wizards-Dream",
    description:
      "Since childhood, I've been captivated by MMORPGs and online role-playing games. The communal bond they foster is what truly draws me in. Hence, I've embarked on a journey to create my own video game from the ground up, complete with its own game engine. This project will delve into the realms of magic and exploration, offering players a rich and immersive experience.",
    techUsed: [
      "HTML5",
      "CSS3",
      "TypeScript",
      "NodeJs",
      "ExpressJS",
      "Socket.IO",
    ],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 5,
    cardName: "BIPOC",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/bipoc.jpeg`,
    released: false,
    releaseDate: "Paused",
    siteUrl: "https://github.com/0112Derrick/BIPOC_TS",
    description:
      "This app is designed to bridge the gap between employers and prospective employees within the green sector. It offers a dedicated space for both parties to discover and post open positions, fostering success and growth. Additionally, the app includes features such as affinity groups, providing a supportive environment for individuals in the BIPOC/LGBTQ+ community to connect with safe spaces and opportunities tailored to their needs.",
    techUsed: ["HTML5", "CSS3", "TypeScript"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 6,
    cardName: "Capitalism 2.0",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/capitalism.jpeg`,
    released: true,
    releaseDate: "05/20/2021",
    siteUrl: "https://cap20.org",
    description: "A corporate web page for the Capitalism 2.0 organization.",
    techUsed: ["HTML5", "CSS3", "TypeScript", "NodeJs", "ExpressJS"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
];
