export const projectCards = [
  {
    id: 0,
    cardName: "Better Stewards",
    techStack: "FrontEnd",
    imageUrl: `${process.env.PUBLIC_URL}/images/better-steward2.avif`,
    released: false,
    releaseDate: "02/17/2024",
    siteUrl: "https://betterstewards.org/",
    description:
      "A website developed in wordpress to bring better promotion to the Better Stewards non-profit organization.",
    techUsed: ["Wordpress", "JavaScript"],
    filters: ["wordpress", "javascript", "frontend"],
  },
  {
    id: 1,
    cardName: "Twitch Bot",
    techStack: "Hybrid",
    imageUrl: `${process.env.PUBLIC_URL}/images/twitch-bot2.avif`,
    released: true,
    releaseDate: "12/20/2023",
    siteUrl: "",
    description:
      "A desktop app developed to interface with Twitch.tv with the purpose of auto playing the twitch game: Pokémon Community Game.",
    techUsed: ["Electron", "JavaScript"],
    filters: ["electron", "javascript", "frontend", "released", "nodejs"],
  },
  {
    id: 2,
    cardName: "Laundromat Express",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/washer2.jpeg`,
    released: false,
    releaseDate: "N/A: In Development",
    siteUrl: "https://github.com/0112Derrick/Laundromat-Hub",
    description: "",
    techUsed: ["ReactJS", "Asp.Net", "Bootstrap"],
    filters: [
      "react",
      "asp.net",
      "javascript",
      "typescript",
      "fullstack",
      "bootstrap",
    ],
  },
  {
    id: 3,
    cardName: "Gees Clippers",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/gee.png`,
    released: false,
    releaseDate: "N/A",
    siteUrl: "https://github.com/0112Derrick/GeesClippersTechTitans-Personal",
    description: "",
    techUsed: ["HTML5", "CSS3", "TypeScript", "NodeJs", "ExpressJS"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 4,
    cardName: "Wizards Dream",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/castle.jpg`,
    released: false,
    releaseDate: "N/A: In Development",
    siteUrl: "https://github.com/0112Derrick/Wizards-Dream",
    description: "",
    techUsed: [
      "HTML5",
      "CSS3",
      "TypeScript",
      "NodeJs",
      "ExpressJS",
      "Socket.IO",
    ],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 5,
    cardName: "BIPOC",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/bipoc.jpeg`,
    released: false,
    releaseDate: "Paused",
    siteUrl: "https://github.com/0112Derrick/BIPOC_TS",
    description: "",
    techUsed: ["HTML5", "CSS3", "TypeScript"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
  {
    id: 6,
    cardName: "Capitalism 2.0",
    techStack: "Fullstack",
    imageUrl: `${process.env.PUBLIC_URL}/images/capitalism.jpeg`,
    released: true,
    releaseDate: "05/20/2021",
    siteUrl: "https://cap20.org",
    description: "",
    techUsed: ["HTML5", "CSS3", "TypeScript", "NodeJs", "ExpressJS"],
    filters: [
      "javascript",
      "typescript",
      "fullstack",
      "html",
      "css",
      "express",
      "nodejs",
    ],
  },
];
